### ISSUE TITLE
Having trouble with travis

### ISSUE THREAD

**Issue by TahsinTariq** [sn99/wasm-template-rust#9]
Hey, so I tried to host my projects on github, but I'm getting this problem in travis:
`Skipping a deployment with the pages provider because this branch is not permitted: main`

I've never used travis CI before. So I don't even know if I'm doing something wrong.

**Comment by sn99** [comment]
Hi, did you make a new branch my name `gh-pages` ? And was the token given all the correct permissions?

**Comment by TahsinTariq** [comment]
Yes, I followed exactly as you instructed in the readme. Still doesn't work.

**Comment by TahsinTariq** [comment]
I got it to work using github actions. I also made it so I don't need to have multiple repos for multiple projects. I can host all rust+wasm projects in one repo under their own directory and github actions takes care of all the deployment. The code from this template was very insightful, so thanks.
I guess this issue can be closed now.
